services:
  bbb-exporter:
    container_name: "bbb-exporter"
    build: ../../
    pull_policy: build
    image: amg-web/bbb-exporter
    network_mode: host
    volumes:
      # Can be removed if `BBB_VERSION_READ_FROM_DISK` is set to false (or omitted).
      - "/etc/bigbluebutton/bigbluebutton-release:/etc/bigbluebutton/bigbluebutton-release:ro"
      
      # Can be removed if `RECORDINGS_METRICS_READ_FROM_DISK` is set to false (or omitted).
      # See https://bigbluebutton-exporter.greenstatic.dev/exporter-user-guide/#optimizations for details.
      - "/var/bigbluebutton:/var/bigbluebutton:ro"
    
    # There can be an issue of DNS resolution if the hostname and the api url is the same. 
    # Docker then advertises the FQDN as a local 127.0.0.1 IP inside the container.
    #extra_hosts: 
    #  - 'host-fqdn:PUBLIC.HOST.IP.ADDRESS'
    #  - 'bbb.example.com:1.2.3.4'  # example
    env_file:
      - .env
    restart: unless-stopped
